---
- name: drush | check if drush exists
  stat: path={{ ansible_env.HOME }}/.composer/vendor/drush/drush/drush
  register: drush

- name: drush | install drush via composer
  command: composer global require drush/drush:6.*
  when: not drush.stat.exists
  tags: drush

- name: drush | set drush to executable
  command: chmod u+x drush chdir={{ ansible_env.HOME }}/.composer/vendor/drush/drush
  when: not drush.stat.exists
  tags: drush

- name: drush | link up the drush command so everyone can run it
  file: src={{ ansible_env.HOME }}/.composer/vendor/drush/drush/drush dest=/usr/bin/drush state=link
  tags: drush
  sudo: true

- name: drush | run drush once as current user to finalise install
  command: drush
  when: not drush.stat.exists
  tags: drush
