---
- name: Install PHP packages
  apt: name={{ item }} state=present force=yes
  with_items:
    - php5
    - php5-cli
    - php5-curl
    - php5-gd

- name: Install Composer
  shell: curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer creates=/usr/local/bin/composer

- name: Add composer vendor directory to path
  lineinfile: dest={{ ansible_env.HOME }}/.bashrc state=present line='export PATH=$PATH:$HOME/.composer/vendor/bin/'

- include: drush.yml
